//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amics
    {
        public int id { get; set; }
        public int usuari1_id { get; set; }
        public int usuari2_id { get; set; }
    
        public virtual Usuaris Usuaris { get; set; }
        public virtual Usuaris Usuaris1 { get; set; }
    }
}
