//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Butaques
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Butaques()
        {
            this.Reserves = new HashSet<Reserves>();
        }
    
        public int butaca_id { get; set; }
        public string fila { get; set; }
        public int numero { get; set; }
        public int espai_id { get; set; }
    
        public virtual Espais Espais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserves> Reserves { get; set; }
    }
}
