//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Esdeveniments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Esdeveniments()
        {
            this.Reserves = new HashSet<Reserves>();
        }
    
        public int event_id { get; set; }
        public string nom { get; set; }
        public string descripcio { get; set; }
        public System.DateTime data_hora { get; set; }
        public string text_promocional { get; set; }
        public string imatge_promocional_url { get; set; }
        public string estat { get; set; }
        public int espai_id { get; set; }
        public int organitzador_id { get; set; }
    
        public virtual Espais Espais { get; set; }
        public virtual Usuaris Usuaris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserves> Reserves { get; set; }
    }
}
