//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espais
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espais()
        {
            this.Butaques = new HashSet<Butaques>();
            this.Esdeveniments = new HashSet<Esdeveniments>();
        }
    
        public int espai_id { get; set; }
        public string nom { get; set; }
        public string ubicacio { get; set; }
        public int metres_quadrats { get; set; }
        public Nullable<int> cadires_fixes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Butaques> Butaques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Esdeveniments> Esdeveniments { get; set; }
    }
}
