//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evencatEntities1 : DbContext
    {
        public evencatEntities1()
            : base("name=evencatEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Amics> Amics { get; set; }
        public virtual DbSet<Butaques> Butaques { get; set; }
        public virtual DbSet<Esdeveniments> Esdeveniments { get; set; }
        public virtual DbSet<Espais> Espais { get; set; }
        public virtual DbSet<Reserves> Reserves { get; set; }
        public virtual DbSet<Usuaris> Usuaris { get; set; }
    }
}
