//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_evencat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserves
    {
        public int reserva_id { get; set; }
        public Nullable<System.DateTime> data_reserva { get; set; }
        public int usuari_id { get; set; }
        public int event_id { get; set; }
        public Nullable<int> butaca_id { get; set; }
    
        public virtual Butaques Butaques { get; set; }
        public virtual Esdeveniments Esdeveniments { get; set; }
        public virtual Usuaris Usuaris { get; set; }
    }
}
